/*
	Onion HTTP server library
	Copyright (C) 2010-2011 David Moreno Montero

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as
	published by the Free Software Foundation, either version 3 of the
	License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU Affero General Public License for more details.

	You should have received a copy of the GNU Affero General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.
	*/

#include <stdio.h>
#include <string.h>
#include <ctype.h>

#include "onion/log.h"
#include "list.h"
#include "block.h"
#include "parser.h"


int work(FILE *in, FILE *out);

int main(int argc, char **argv){
	if (argc!=3){
		ONION_ERROR("Usage: otemplate <inputfile> <outputfile>");
		return 1;
	}
	
	FILE *in;
	if (strcmp(argv[1], "-")==0)
		in=stdin;
	else
		in=fopen(argv[1], "rt");
	
	FILE *out;
	if (strcmp(argv[2], "-")==0)
		out=stdout;
	else
		out=fopen(argv[2], "wt");
	
	if (!in || !out){
		ONION_ERROR("Error opening input or output file");
		return 1;
	}
	
	int error=work(in,out);
	
	fclose(in);
	fclose(out);
	
	return error;
}


int work(FILE *in, FILE *out){
	parser_status status;
	memset(&status, 0, sizeof(status));
	status.in=in;
	status.out=out;
	status.mode=TEXT;
	status.blocks=list_new((void*)block_free);
	status.status=0;
	list_add(status.blocks, block_new(0));
	
	parse_template(&status);
	
	if (status.status){
		ONION_ERROR("Parsing error");
		list_free(status.blocks);
		return status.status;
	}
	
	fprintf(out,
"/** Autogenerated by otemplate v. 0.0.0 */\n"
"\n"
"#include <libintl.h>\n"
"#include <onion/onion.h>\n"
"#include <onion/dict.h>\n"
"\n"
"int work(onion_dict *context, onion_request *req){\n"
"  const char *tmp;\n"
"  onion_response *res=onion_response_new(req);\n"
"  onion_response_write_headers(res);\n\n");
	
	list_loop(status.blocks, (void*)write_block, &status);

	fprintf(out,"\n"
"  return onion_response_free(res);\n"
"}\n");

	list_free(status.blocks);
	
	return status.status;
}

/**
 * @short Main parsing loop.
 */
void parse_template(parser_status *status){
	int c;
	while ( (status->c=fgetc(status->in)) >= 0){
		c=status->c;
		switch(status->mode){
			case TEXT:
				if (c=='{')
					set_mode(status, BEGIN);
				else
					add_char(status, c);
				break;
			case BEGIN:
				if (c=='{')
					set_mode(status, TAG);
				else if (c=='%')
					set_mode(status, CODE);
				else{
					set_mode(status, TEXT);
					add_char(status, '{');
					add_char(status, c);
				}
				break;
			case TAG:
				if (c=='}')
					set_mode(status, END_TAG);
				else
					add_char(status, c);
				break;
			case CODE:
				if (c=='%')
					set_mode(status, END_CODE);
				else
					add_char(status, c);
				break;
			case END_TAG:
				if (c=='}')
					set_mode(status, TEXT);
				else{
					set_mode(status, TAG);
					add_char(status, '}');
					add_char(status, c);
				}
				break;
			case END_CODE:
				if (c=='}')
					set_mode(status, TEXT);
				else{
					set_mode(status, END_CODE);
					add_char(status, '%');
					add_char(status, c);
				}
				break;
			default:
				ONION_ERROR("Unknown mode %d",status->mode);
				status->status=1;
				return;
		}
	}
}

void write_tag(parser_status *st, block *b){
	block_safe_for_printf(b);
	fprintf(st->out, 
"  tmp=onion_dict_get(context, \"%s\");\n"
"  if (tmp)\n"
"    onion_response_write0(res, tmp);\n", b->data);
}

void write_block(parser_status *st, block *b){
	int mode=(long int)b->extra;
	switch(mode){
		case TEXT:
			if (b->pos){
				int oldl=b->pos;
				block_safe_for_printf(b);
				fprintf(st->out, "  onion_response_write(res, \"%s\", %d);\n", b->data, oldl);
			}
			break;
		case TAG:
			write_tag(st, b);
			break;
		case CODE:
			write_code(st, b);
			break;
	}
}

void add_char(parser_status *st, char c){
	block *last=st->blocks->tail->data;
	block_add_char(last, c);
}

void set_mode(parser_status *status, int mode){
	status->mode=mode;
	if (mode<16)
		list_add(status->blocks, block_new((void*)(long int)mode));
}
