Document: libonion
Title: Debian libonion Manual
Author: <insert document author here>
Abstract: This manual describes what libonion is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libonion/libonion.sgml.gz

Format: postscript
Files: /usr/share/doc/libonion/libonion.ps.gz

Format: text
Files: /usr/share/doc/libonion/libonion.text.gz

Format: HTML
Index: /usr/share/doc/libonion/html/index.html
Files: /usr/share/doc/libonion/html/*.html
